# Generated by Django 5.2.3 on 2025-08-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('situation', models.IntegerField(choices=[(1, 'alerta'), (2, 'atencao'), (3, 'mobilizacao'), (4, 'normalidade')], default=4)),
                ('type', models.CharField(max_length=80)),
                ('neighborhood', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('neighborhood', models.CharField()),
                ('rain', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('elevation', models.FloatField(null=True)),
                ('pressure', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField()),
                ('flood', models.FloatField()),
                ('probability', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Forecasts',
                'unique_together': {('latitude', 'longitude', 'date')},
            },
        ),
    ]
