# Generated by Django 5.2.3 on 2025-08-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_occurrence_weather_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='river_disrcharge',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
