# Generated by Django 5.2.3 on 2025-08-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_camera_flooddetectionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='flooddetectionrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flood_detections/%Y/%m/%d/'),
        ),
    ]
