# Generated by Django 5.2.3 on 2025-08-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_weather_river_disrcharge_weather_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='river_disrcharge',
            new_name='river_discharge',
        ),
    ]
