# Generated by Django 5.2.3 on 2025-08-25 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_flooddetectionrecord_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flooddetectionrecord',
            name='camera',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='FloodDetectionRecord',
        ),
    ]
