# Generated by Django 5.2.3 on 2025-08-27 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_flooddetectionrecord_camera_delete_camera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'OFFLINE')], default=3)),
                ('video_url', models.CharField(max_length=512, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('address_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloodDetectionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_flooded', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('prob_normal', models.FloatField()),
                ('prob_flooded', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='flood_detections/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='core.camera')),
            ],
            options={
                'verbose_name': 'Flood detection record',
                'verbose_name_plural': 'Flood detection records',
                'indexes': [models.Index(fields=['created_at'], name='core_floodd_created_5e121b_idx'), models.Index(fields=['confidence'], name='core_floodd_confide_477f01_idx')],
            },
        ),
    ]
