# Generated by Django 5.2.3 on 2025-08-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_river_disrcharge_weather_river_discharge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Occurrence',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
