# Generated by Django 5.2.3 on 2025-08-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_occurrence_delete_weather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
