# Generated by Django 5.2.6 on 2025-09-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_forecast'),
        ('core', '0006_remove_flooddetectionrecord_camera_delete_camera_and_more'),
    ]

    operations = [
    ]
