# Generated by Django 5.2.6 on 2025-09-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20250908_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
