# Generated by Django 5.2.3 on 2025-08-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='neighborhood',
            field=models.CharField(choices=[('Adhemar Garcia', 'Adhemar Garcia'), ('América', 'América'), ('Anita Garibaldi', 'Anita Garibaldi'), ('Atiradores', 'Atiradores'), ('Aventureiro', 'Aventureiro'), ('Boa Vista', 'Boa Vista'), ('Boehmerwaldt', 'Boehmerwaldt'), ('Bom Retiro', 'Bom Retiro'), ('Bucarein', 'Bucarein'), ('Centro', 'Centro'), ('Comasa', 'Comasa'), ('Costa E Silva', 'Costa E Silva'), ('Dona Francisca', 'Dona Francisca'), ('Espinheiros', 'Espinheiros'), ('Floresta', 'Floresta'), ('Fátima', 'Fátima'), ('Glória', 'Glória'), ('Guanabara', 'Guanabara'), ('Iririu', 'Iririu'), ('Itaum', 'Itaum'), ('Itinga', 'Itinga'), ('Jardim-Iririú', 'Jardim-Iririú'), ('Jardim Paraíso', 'Jardim Paraíso'), ('Jardim Sofia', 'Jardim Sofia'), ('Jarivatuba', 'Jarivatuba'), ('João Costa', 'João Costa'), ('Morro Do Meio', 'Morro Do Meio'), ('Nova Brasília', 'Nova Brasília'), ('Paranaguamirim', 'Paranaguamirim'), ('Parque Guaraní', 'Parque Guaraní'), ('Petrópolis', 'Petrópolis'), ('Pirabeiraba', 'Pirabeiraba'), ('Profipo', 'Profipo'), ('Rio Bonito', 'Rio Bonito'), ('Saguaçu', 'Saguaçu'), ('Santa Catarina', 'Santa Catarina'), ('Santo Antônio', 'Santo Antônio'), ('São Marcos', 'São Marcos'), ('Ulysses Guimarães', 'Ulysses Guimarães'), ('Vila Cubatão', 'Vila Cubatão'), ('Vila Nova', 'Vila Nova'), ('Zona Industrial 1', 'Zona Industrial 1'), ('Zona Industrial 2', 'Zona Industrial 2')], max_length=22),
        ),
    ]
