# Generated by Django 5.2.3 on 2025-08-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_alter_occurrence_neighborhood'),
        ('weather', '0002_weather_unique_weather_per_day_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weather', to='weather.weather'),
        ),
    ]
