# Generated by Django 5.2.3 on 2025-08-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0003_occurrence_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='weather',
        ),
    ]
