# Generated by Django 5.2.5 on 2025-09-11 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addressing', '0009_remove_address_addressing__neighbo_50804d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flood_Point_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.IntegerField(choices=[(1, 'Joinville'), (2, 'Araquari')], default=1)),
                ('possibility', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('props', models.JSONField()),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addressing.neighborhood')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addressing.region')),
            ],
        ),
    ]
