# Generated by Django 5.2.6 on 2025-09-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood_point_registering', '0002_city_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flood_point_register',
            name='city',
        ),
        migrations.RemoveField(
            model_name='flood_point_register',
            name='city_ref',
        ),
    ]
