# Generated by Django 5.2.6 on 2025-09-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_point_registering', '0003_remove_flood_point_register_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flood_point_register',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='flood_point_register',
            name='finished_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
