# Generated by Django 5.2.3 on 2025-08-25 03:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'OFFLINE')], default=3)),
                ('video_url', models.CharField(max_length=512)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('address_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloodDetectionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_flooded', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('prob_normal', models.FloatField()),
                ('prob_flooded', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='flood_detections/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='flood_camera_monitoring.camera')),
            ],
            options={
                'verbose_name': 'Flood detection record',
                'verbose_name_plural': 'Flood detection records',
                'indexes': [models.Index(fields=['created_at'], name='flood_camer_created_eb5c5c_idx'), models.Index(fields=['confidence'], name='flood_camer_confide_59b0da_idx')],
            },
        ),
    ]
