# Generated by Django 5.2.3 on 2025-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_camera_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='video_url',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
