# Generated by Django 5.2.5 on 2025-08-31 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0003_remove_address_addressing__region__6f3866_idx_and_more'),
        ('flood_camera_monitoring', '0002_alter_camera_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='addressing.neighborhood'),
        ),
    ]
