# Generated by Django 5.2.5 on 2025-09-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0009_remove_address_addressing__neighbo_50804d_idx_and_more'),
        ('flood_camera_monitoring', '0003_camera_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='camera',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='addressing.address'),
        ),
    ]
