# Generated by Django 5.2.5 on 2025-09-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_camera_monitoring', '0004_remove_camera_address_id_remove_camera_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flooddetectionrecord',
            name='medium',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
