# Generated by Django 5.2.6 on 2025-09-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flood_camera_monitoring", "0006_flooddetectionrecord_prob_medium"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="video_url",
        ),
        migrations.AddField(
            model_name="camera",
            name="video_embed",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="camera",
            name="video_hls",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
