# Generated by Django 5.2.6 on 2025-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_camera_monitoring', '0007_remove_camera_video_url_camera_video_embed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='video_embed',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='video_hls',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
