# Generated by Django 5.2.6 on 2025-09-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0009_remove_address_addressing__neighbo_50804d_idx_and_more'),
        ('flood_camera_monitoring', '0008_alter_camera_video_embed_alter_camera_video_hls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='address',
        ),
        migrations.AddField(
            model_name='camera',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='addressing.neighborhood'),
        ),
    ]
