# Generated by Django 5.2.3 on 2025-08-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('neighborhood', models.CharField()),
                ('rain', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('elevation', models.FloatField(null=True)),
                ('pressure', models.FloatField(null=True)),
            ],
        ),
    ]
