# Generated by Django 5.2.6 on 2025-09-15 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=300, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('google_sub', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('profile_picture', models.URLField(blank=True, max_length=512)),
                ('type', models.CharField(choices=[('admin', 'ADMIN'), ('standard', 'STANDARD')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['google_sub'], name='users_user_google__d2388c_idx')],
            },
        ),
    ]
