# Generated by Django 5.2.5 on 2025-08-28 02:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('neighborhood', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='Brazil', max_length=120)),
                ('zipcode', models.CharField(blank=True, max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('region_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='addressing__city_ee06f2_idx'), models.Index(fields=['zipcode'], name='addressing__zipcode_804c21_idx'), models.Index(fields=['neighborhood'], name='addressing__neighbo_583e79_idx'), models.Index(fields=['latitude', 'longitude'], name='addressing__latitud_7a5597_idx'), models.Index(fields=['region_id'], name='addressing__region__6f3866_idx')],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('geometry', models.JSONField()),
                ('bbox_min_lon', models.FloatField()),
                ('bbox_min_lat', models.FloatField()),
                ('bbox_max_lon', models.FloatField()),
                ('bbox_max_lat', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='addressing__city_46526e_idx'), models.Index(fields=['bbox_min_lon', 'bbox_max_lon'], name='addressing__bbox_mi_a6581f_idx'), models.Index(fields=['bbox_min_lat', 'bbox_max_lat'], name='addressing__bbox_mi_eea87a_idx')],
            },
        ),
    ]
