# Generated by Django 5.2.3 on 2025-08-28 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('bbox_min_lon', models.FloatField(blank=True, null=True)),
                ('bbox_min_lat', models.FloatField(blank=True, null=True)),
                ('bbox_max_lon', models.FloatField(blank=True, null=True)),
                ('bbox_max_lat', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.AddIndex(
            model_name='neighborhood',
            index=models.Index(fields=['city'], name='addressing__city_8d0354_idx'),
        ),
        migrations.AddIndex(
            model_name='neighborhood',
            index=models.Index(fields=['name'], name='addressing__name_67757a_idx'),
        ),
        migrations.AddField(
            model_name='address',
            name='neighborhood_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='addressing.neighborhood'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['neighborhood_ref'], name='addressing__neighbo_50804d_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['city'], name='addressing__city_bcd318_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['bbox_min_lon', 'bbox_max_lon'], name='addressing__bbox_mi_cb5566_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['bbox_min_lat', 'bbox_max_lat'], name='addressing__bbox_mi_28f31b_idx'),
        ),
    ]
