# Generated by Django 5.2.5 on 2025-08-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0002_neighborhood_region_delete_area_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='addressing__region__6f3866_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='region_id',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighborhoods', to='addressing.region'),
        ),
        migrations.AddIndex(
            model_name='neighborhood',
            index=models.Index(fields=['region'], name='addressing__region__c292cf_idx'),
        ),
    ]
