# Generated by Django 5.2.5 on 2025-08-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0003_remove_address_addressing__region__6f3866_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
