# Generated by Django 5.2.5 on 2025-08-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0004_neighborhood_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='area_km2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='bbox_max_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='bbox_max_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='bbox_min_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='bbox_min_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='centroid_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='centroid_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='neighborhood',
            index=models.Index(fields=['bbox_min_lon', 'bbox_max_lon'], name='addressing__bbox_mi_2a2f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='neighborhood',
            index=models.Index(fields=['bbox_min_lat', 'bbox_max_lat'], name='addressing__bbox_mi_aa6a49_idx'),
        ),
        migrations.AddConstraint(
            model_name='neighborhood',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='uniq_neigh_city_name'),
        ),
    ]
