# Generated by Django 5.2.5 on 2025-08-31 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0005_neighborhood_area_km2_neighborhood_bbox_max_lat_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='neighborhood',
            name='uniq_neigh_city_name',
        ),
        migrations.RemoveIndex(
            model_name='neighborhood',
            name='addressing__bbox_mi_2a2f9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='neighborhood',
            name='addressing__bbox_mi_aa6a49_idx',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='area_km2',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='bbox_max_lat',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='bbox_max_lon',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='bbox_min_lat',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='bbox_min_lon',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='centroid_lat',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='centroid_lon',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='geometry',
        ),
    ]
