# Generated by Django 5.2.5 on 2025-08-31 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0006_remove_neighborhood_uniq_neigh_city_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='region',
            name='addressing__bbox_mi_cb5566_idx',
        ),
        migrations.RemoveIndex(
            model_name='region',
            name='addressing__bbox_mi_28f31b_idx',
        ),
        migrations.RemoveField(
            model_name='region',
            name='bbox_max_lat',
        ),
        migrations.RemoveField(
            model_name='region',
            name='bbox_max_lon',
        ),
        migrations.RemoveField(
            model_name='region',
            name='bbox_min_lat',
        ),
        migrations.RemoveField(
            model_name='region',
            name='bbox_min_lon',
        ),
        migrations.RemoveField(
            model_name='region',
            name='geometry',
        ),
    ]
