# Generated by Django 5.2.5 on 2025-08-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0007_remove_region_addressing__bbox_mi_cb5566_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='area_km2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
