# Generated by Django 5.2.5 on 2025-09-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0008_neighborhood_area_km2'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='addressing__neighbo_50804d_idx',
        ),
        migrations.RenameIndex(
            model_name='address',
            new_name='addressing__neighbo_949d5a_idx',
            old_name='addressing__neighbo_583e79_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='neighborhood_ref',
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='addressing.neighborhood'),
        ),
    ]
