# Generated by Django 5.2.6 on 2025-09-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0010_city_and_links'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='addressing__name_92704e_idx'),
        ),
    ]
