# Generated by Django 5.2.3 on 2025-08-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weather',
            constraint=models.UniqueConstraint(fields=('date', 'latitude', 'longitude', 'neighborhood'), name='unique_weather_per_day_location'),
        ),
    ]
