# Generated by Django 5.2.3 on 2025-08-30 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0004_remove_occurrence_weather'),
        ('weather', '0002_weather_unique_weather_per_day_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrence', to='occurrences.occurrence'),
        ),
    ]
